### ISSUE TITLE
Restrict the character limit for application alias to 20

### ISSUE THREAD

**Issue by eriklg** [apprenda/Apprenda-TFS-Integration#14]
The Apprenda Platform uses the application alias as part of the URL published. This bounds the character limit to what is supported in an URL. The TFS plugin should enforce a limit to ensure that the configuration is consistent with what the platform supports.

**Comment by eriklg** [comment]
@dutronlabs Fix for this pushed in aliascount branch. Please review and I can make a pull request.

**Comment by TetsujinOni** [comment]
The aliascount branch with this fix was merged to master 26 February 2017. Closing.
