### ISSUE TITLE
Expose Properties to separate Version Alias and Version Name

### ISSUE THREAD

**Issue by bherdan** [apprenda/Apprenda-TFS-Integration#18]
As of Apprenda 7.2 only letters and numbers are supported as a part of the version alias as this might be used as a part of a URL for subdomain deployments. 
For scenarios where a Release Manager would like to use the Build Number (which can include dots) as a part of release, we should allow a separation of parameters so that they can provide the build number (say 1.2.3) as a version name, and retain a self-incrementing version alias that can be used for the URL.

**Comment by michmike** [comment]
@bherdan essentially you are asking to expose another property for each app, the version name which a build manager can populate with anything they want. everything else will be unchanged.

**Comment by bherdan** [comment]
@michmike that is correct.
