### ISSUE TITLE
Expose ability to retain Published Instance Count when patching

### ISSUE THREAD

**Issue by bherdan** [apprenda/Apprenda-TFS-Integration#19]
While patching an application to the Published stage, I should be able to state whether I want to default to 1 instance (or whatever else is provided in the manifest), or use the current Published instance's settings. This can be achieved by using the "useScalingSettingsFrom=Published" flag in the REST call.
We should expose a checkbox to define whether this setting is used or not as a part of the request of creating and promoting a new version.

**Comment by TetsujinOni** [comment]
Fixed in 1.2
