### ISSUE TITLE
fix promote.ps1, clean up parameters

### ISSUE THREAD

**Issue by dutronlabs** [apprenda/Apprenda-TFS-Integration#8]

**Comment by dutronlabs** [comment]
moving out to 1.2 - we'll handle this in the next release

**Comment by TetsujinOni** [comment]
Reviewing because cleaning up deployment issues related to promotion failure from team resource limits in deploy.ps1 may have fixed this by fixing common.ps1.

**Comment by TetsujinOni** [comment]
Investigation finally done, this needs to be implemented as promotion logic having been copy-pasted from the demotion script.

**Comment by TetsujinOni** [comment]
Work in 842a8d364f275f907ba3848b866c8cab28671c22

**Comment by TetsujinOni** [comment]
More work coming in additional commit.
